library('devtools')
## replace with your path to ars
setwd('~/Dropbox/stat243_final_project/243FinalProject/ars')
load_all()
devtools::test()
check()

sv <- ars(dnorm, c(-Inf,Inf), n = 100000, MAX_HOLDING = 100000)
hist(sv, col='blue', prob=TRUE, breaks=100, xlim=c(-3,3), xlab = "x", main="Histogram of Values Sampled with ARS")
x <- seq(-4,4,.01)
lines(x, dnorm(x),lty=5,lwd=2,col="red")
legend("topright", c("Sample Values", "Analytical Form"), col=c("blue", "red"), lwd=2, cex = 0.7)

sv <- ars(dunif, c(3,4), n = 100000, nGroup = 1, min=3, max=4, MAX_HOLDING = 100)
hist(sv, col='blue', prob=TRUE, breaks=50, xlab = "x", main="Histogram of Values Sampled with ARS")
x <- seq(3,4,.01)
lines(x, dunif(x),lty=5,lwd=2,col="red")
legend("bottomright", c("Sample Values", "Analytical Form"), col=c("blue", "red"), lwd=2, cex = 0.7)

sv <- ars(dexp, c(0,Inf), n = 5000, rate=1, nGroup = 10)
hist(sv, col='blue', prob=TRUE, breaks=100, xlim = c(0,3), xlab = "x", main="Histogram of Values Sampled with ARS")
x <- seq(0,6,.01)
lines(x, dexp(x),lty=5,lwd=2,col="red")
legend("topright", c("Sample Values", "Analytical Form"), col=c("blue", "red"), lwd=2, cex = 0.7)

sv <- ars(dchisq, c(0.0,Inf), n = 100000, df = 3)
hist(sv, col='blue', prob=TRUE, breaks=100, xlim = c(0,12), xlab = "x", main="Histogram of Values Sampled with ARS")
x <- seq(0,12,.01)
lines(x, dchisq(x, df = 3),lty=5,lwd=2,col="red")
legend("topright", c("Sample Values", "Analytical Form"), col=c("blue", "red"), lwd=2, cex = 0.7)
